logging:
  level:
    keycloak-config-cli: debug
    http: info

keycloak:
  url: http://localhost:8080/auth
  user: admin
  password: admin
  ssl-verify: false

configuration:
  env: local
  advanced-settings:
    operator-max-version:
  operators:
    - realm: operator1
      back-office-url: http://localhost:4200
      reset-version:
