logging:
  level:
    keycloak-config-cli: debug
    http: info

keycloak:
  url: https://staging.security.etal-engine.com/auth
  user: admin
  password: admin
  ssl-verify: false

configuration:
  env: staging
  advanced-settings:
    operator-max-version:
  operators:
    - realm: operator1
      back-office-url: http://operator1.staging.admin.etal-engine.com
      reset-version:
